version: '3.4'

networks:
  periferia:
      driver: bridge

services:

  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=periferiaStore
    ports:
      - 5432:5432
    networks:
      - periferia
    volumes: 
      - db:/var/lib/postgresql/data

  backend:
    image: server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
    - 5000:5000
    networks:
      - periferia
    links:
      - database
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/periferiaStore?schema=public?encrypt=false
    depends_on:
      - database

  frontend:
    image: app
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - 80:80
    networks:
      - periferia
    links:
      - backend
    depends_on:
      - backend

volumes:
  db:
    driver: br