export const products = [
    {
        id: 1,
        title: "iPhone 13",
        description: "An apple mobile which is nothing like apple",
        price: 699,
        brand: "Apple",
        thumbnail: "https://res.cloudinary.com/dzanaidkk/image/upload/v1673382501/iphone-13_x143mn.jpg",
    },
    {
        id: 2,
        title: "iPhone 12",
        description: "An apple mobile which is nothing like apple",
        price: 599,
        brand: "Apple",
        thumbnail: "https://res.cloudinary.com/dzanaidkk/image/upload/v1673382501/iphone-12_dwkrik.jpg",
    },
    {
        id: 3,
        title: "iPhone SE",
        description: "An apple mobile which is nothing like apple",
        price: 429,
        brand: "Apple",
        thumbnail: "https://res.cloudinary.com/dzanaidkk/image/upload/v1673382501/iphone-se_ieqnap.jpg",
    },
    {
        id: 4,
        title: "iPhone 13 mini",
        description: "An apple mobile which is nothing like apple",
        price: 599,
        brand: "Apple",
        thumbnail: "https://res.cloudinary.com/dzanaidkk/image/upload/v1673382501/iphone-13-mini_jpcudp.jpg",
    },
    {
        id: 5,
        title: "iPhone 14",
        description: "An apple mobile which is nothing like apple",
        price: 799,
        brand: "Apple",
        thumbnail: "https://res.cloudinary.com/dzanaidkk/image/upload/v1673382501/iphone-14_ngpsdv.jpg",
    },
    {
        id: 6,
        title: "iPhone 14 Pro",
        description: "An apple mobile which is nothing like apple",
        price: 899,
        brand: "Apple",
        thumbnail: "https://res.cloudinary.com/dzanaidkk/image/upload/v1673382501/iphone-14-pro_tvrtpf.jpg",
    },
    {
        id: 7,
        title: "iPhone 14 Pro Max",
        description: "An apple mobile which is nothing like apple",
        price: 799,
        brand: "Apple",
        thumbnail: "https://res.cloudinary.com/dzanaidkk/image/upload/v1673382501/iphone-14-pro-max_lgrpih.jpg",
    },
    {
        id: 8,
        title: "iPhone 14 Plus",
        description: "An apple mobile which is nothing like apple",
        price: 899,
        brand: "Apple",
        thumbnail: "https://res.cloudinary.com/dzanaidkk/image/upload/v1673382501/iphone-14-plus_qlxcbl.jpg",
    }
]